### PR TITLE
PFCF 491 - Form 3 Schedule 5 Missing Note Boxes

### PR DESCRIPTION
**Pull request by JTraill**
refactor: add in missing side note boxes that werent caught by QA

### CODE REVIEW

**Comment by JTraill** [comment]
See one more issue im going to fix in this PR as well

**Comment by JTraill** [comment]
Need to grey out the answer boxes as well

**Review by JonTaylorBCGov2 — APPROVED** [review]

**Comment by JTraill** [comment]
Finalizing a bit of styling i noticed not caught by QA

**Comment by JTraill** [comment]
Done, reopening

**Pull request merged**
